# Generated by Django 5.1.3 on 2024-11-10 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("fname", models.CharField(max_length=200)),
                ("lname", models.CharField(max_length=200)),
                ("advisor", models.CharField(max_length=200)),
                ("f_path", models.FileField(upload_to="documents/")),
            ],
        ),
        migrations.CreateModel(
            name="Doc_theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme_name", models.CharField(max_length=200)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="papers.document",
                    ),
                ),
            ],
        ),
    ]
